WebApplication1/Areas/Admin/Controllers/ADPostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models;
using X.PagedList;
namespace WebApplication1.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ADPostsController : Controller
    {
        private readonly ThaoDuocMarketContext _context;

        public ADPostsController(ThaoDuocMarketContext context)
        {
            _context = context;
        }

        // GET: Admin/ADPosts
        public async Task<IActionResult> Index(int? page)
        {
            int pageNumber = page ?? 1; // Nếu không có trang nào được chỉ định, mặc định là trang 1
            int pageSize = 5; // Số lượng item mỗi trang
            var posts = _context.Posts.OrderBy(p => p.CreateDate).ToPagedList(pageNumber, pageSize);
            return View(posts);
        }

        // GET: Admin/ADPosts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .FirstOrDefaultAsync(m => m.PostId == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // GET: Admin/ADPosts/Create
        public IActionResult Create()
        {
            return View();
        }



        private async Task<string> SaveImage(IFormFile thumb)
        {
            var savePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/thumb/post");

            // Đảm bảo thư mục tồn tại
            if (!Directory.Exists(savePath))
            {
                Directory.CreateDirectory(savePath);
            }

            var fileName = Path.GetFileName(thumb.FileName);
            var filePath = Path.Combine(savePath, fileName);

            using (var fileStream = new FileStream(filePath, FileMode.Create))
            {
                await thumb.CopyToAsync(fileStream);
            }
            return "/thumb/post/" + fileName;
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PostId,Title,ShortContents,Contents,Thumb,Published,CreateDate,Author,AccountId,Tags")] Post post, IFormFile thumb)
        {
            if (ModelState.IsValid)
            {
                // Kiểm tra xem người dùng đã tải lên ảnh hay chưa
                if (thumb != null && thumb.Length > 0)
                {
                    // Lưu ảnh và lấy đường dẫn
                    var thumbPath = await SaveImage(thumb);
                    // Lưu đường dẫn vào thuộc tính Thumb của bài viết
                    post.Thumb = thumbPath;
                }
                post.CreateDate = DateTime.Now;
                _context.Add(post);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(post);
        }


        // GET: Admin/ADPosts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.FindAsync(id);
            if (post == null)
            {
                return NotFound();
            }
            return View(post);
        }

        // POST: Admin/ADPosts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PostId,Title,ShortContents,Contents,Thumb,Published,CreateDate,Author,AccountId,Tags")] Post post, IFormFile thumb)
        {
            if (id != post.PostId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // Nếu có tệp ảnh mới được tải lên
                    if (thumb != null && thumb.Length > 0)
                    {
                        // Lưu ảnh mới và lấy đường dẫn
                        var thumbPath = await SaveImage(thumb);
                        // Cập nhật đường dẫn ảnh trong bài viết
                        post.Thumb = thumbPath;
                    }
                    else
                    {
                        // Giữ lại đường dẫn ảnh cũ nếu không có ảnh mới được tải lên
                        var existingPost = await _context.Posts.AsNoTracking().FirstOrDefaultAsync(p => p.PostId == id);
                        post.Thumb = existingPost?.Thumb;
                    }

                    _context.Update(post);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostExists(post.PostId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(post);
        }


        // GET: Admin/ADPosts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .FirstOrDefaultAsync(m => m.PostId == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // POST: Admin/ADPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var post = await _context.Posts.FindAsync(id);
            if (post != null)
            {
                _context.Posts.Remove(post);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PostExists(int id)
        {
            return _context.Posts.Any(e => e.PostId == id);
        }
    }
}

WebApplication1/Areas/Admin/Controllers/ADProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models;
using X.PagedList;
using static WebApplication1.Areas.Admin.Controllers.ADProductsController;

namespace WebApplication1.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ADProductsController : Controller
    {
        private readonly ThaoDuocMarketContext _context;
        private object status;
        
        

        public ADProductsController(ThaoDuocMarketContext context)
        {
            _context = context;
        }

        // GET: Admin/ADProducts

        public ActionResult Index(int page = 1, int CatID = 0, string search = "")
        {
            var pageNumber = page;
            var pageSize = 10;

            IQueryable<Product> productsQuery = _context.Products
                                            .AsNoTracking()
                                            .Include(x => x.Cat)
                                            .OrderByDescending(x => x.ProductId);

            if (CatID != 0)
            {
                productsQuery = productsQuery.Where(x => x.CatId == CatID);
            }

            if (!string.IsNullOrEmpty(search))
            {
                productsQuery = productsQuery.Where(p => p.ProductName.Contains(search) || p.Description.Contains(search));
            }

            List<Product> lsProduct = productsQuery.ToList();

            PagedList<Product> models = new PagedList<Product>(lsProduct.AsQueryable(), pageNumber, pageSize);

            ViewBag.CurrentCateID = CatID;
            ViewBag.CurrentPage = pageNumber;
            ViewData["CatId"] = new SelectList(_context.Categories, "CatId", "CatName", CatID);

            return View(models);
        }


        // GET: Admin/ADProducts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Cat)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["CategoryName"] = product.Cat?.CatName;
            return View(product);
        }


        


        // GET: Admin/ADProducts/Create
        public IActionResult Create()
        {
            ViewData["CatId"] = new SelectList(_context.Categories, "CatId", "CatName");
            return View();
        }

        // POST: Admin/ADProducts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Product product, IFormFile thumbUrl)
        {
            if (ModelState.IsValid)
            {
                if (thumbUrl != null && thumbUrl.Length > 0)
                {
                    // Lưu hình ảnh đại diện
                    product.Thumb = await SaveImage(thumbUrl);
                }

                product.DateModified = DateTime.Now;
                product.DateCreate = DateTime.Now;

                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CatId"] = new SelectList(_context.Categories, "CatId", "CatName", product.CatId);
            return View(product);
        }

        private async Task<string> SaveImage(IFormFile thumb)
        {
            var savePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/thumb/product");

            // Đảm bảo thư mục tồn tại
            if (!Directory.Exists(savePath))
            {
                Directory.CreateDirectory(savePath);
            }

            var fileName = Path.GetFileName(thumb.FileName);
            var filePath = Path.Combine(savePath, fileName);

            using (var fileStream = new FileStream(filePath, FileMode.Create))
            {
                await thumb.CopyToAsync(fileStream);
            }
            return "/thumb/product/" + fileName;
        }


        // GET: Admin/ADProducts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["CatId"] = new SelectList(_context.Categories, "CatId", "CatName", product.CatId);
            return View(product);
        }

        // POST: Admin/ADProducts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductId,ProductName,ShortDesc,Description,CatId,Price,Discount,Thumb,DateCreate,DateModified,BestSeller,HomeFlag,Active,Tags,UnitsInStock")] Product product, IFormFile thumbUrl)
        {
            if (id != product.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (thumbUrl != null)
                    {
                        // Lưu hình ảnh đại diện mới
                        product.Thumb = await SaveImage(thumbUrl);
                    }
                    product.DateModified =DateTime.Now;
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                   
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CatId"] = new SelectList(_context.Categories, "CatId", "CatName", product.CatId);
            return View(product);
        }

        // GET: Admin/ADProducts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Cat)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Admin/ADProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            if (product != null)
            {
                _context.Products.Remove(product);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.ProductId == id);
        }

        public IActionResult Filtter(int CatID = 0)
        {
            var url = $"/Admin/AdminProducts?CatID={CatID}";
            if (CatID == 0)
            {
                url = "/Admin/AdminProducts";
            }
            return Json(new { status = "success", redirectUrl = url });
        }
    }
}

WebApplication1/Areas/Admin/Views/Shared/_SideBarPartialView.cshtml
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="index.html">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Interface
    </div>

    <!-- Nav Item - Quản lý quyền truy cập -->
    <li class="nav-item">
        <a class="nav-link" asp-area="Admin" asp-controller="ADRoles" asp-action="Index">
            <i class="fas fa-fw fa-user-shield"></i>
            <span>Quản lý quyền truy cập</span>
        </a>
    </li>

    <!-- Nav Item - Quản lý tài khoản -->
    <li class="nav-item">
        <a class="nav-link" asp-area="Admin" asp-controller="ADAccounts" asp-action="Index">
            <i class="fas fa-fw fa-house-user"></i>
            <span>Quản lý tài khoản</</span>
        </a>
    </li>

    <!-- Nav Item - Quản lý khách hàng -->
    <li class="nav-item">
        <a class="nav-link" asp-area="Admin" asp-controller="ADCustomers" asp-action="Index">
            <i class="fa fa-fw fa-user"></i>
            <span>Quản lý khách hàng</</span>
        </a>
    </li>

    <!-- Nav Item - Quản lý sản phẩm -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePlant"
           aria-expanded="true" aria-controls="collapsePlant">
            <i class="fa fa-fw fa-seedling"></i>
            <span>Quản lý sản phẩm</span>
        </a>
        <div id="collapsePlant" class="collapse" aria-labelledby="headingPlant" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Danh mục quản lý:</h6>
                <a class="collapse-item" asp-area="Admin" asp-controller="ADProducts" asp-action="Index">Danh sách sản phẩm</a>
                <a class="collapse-item" asp-area="Admin" asp-controller="ADCategories" asp-action="Index">Danh mục sản phẩm</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Quản lý bài viết -->
    <li class="nav-item">
        <a class="nav-link" asp-area="Admin" asp-controller="ADPosts" asp-action="Index">
            <i class="fa fa-fw fa-paper-plane"></i>
            <span>Quản lý bài viết</</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Addons
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
           aria-expanded="true" aria-controls="collapsePages">
            <i class="fas fa-fw fa-folder"></i>
            <span>Pages</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Login Screens:</h6>
                <a class="collapse-item" href="login.html">Login</a>
                <a class="collapse-item" href="register.html">Register</a>
                <a class="collapse-item" href="forgot-password.html">Forgot Password</a>
                <div class="collapse-divider"></div>
                <h6 class="collapse-header">Other Pages:</h6>
                <a class="collapse-item" href="404.html">404 Page</a>
                <a class="collapse-item" href="blank.html">Blank Page</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Charts -->
    <li class="nav-item">
        <a class="nav-link" href="charts.html">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Charts</span>
        </a>
    </li>

    <!-- Nav Item - Tables -->
    <li class="nav-item">
        <a class="nav-link" href="tables.html">
            <i class="fas fa-fw fa-table"></i>
            <span>Tables</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>